# Generated by Django 2.1.7 on 2019-03-30 22:01

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
    ]
