# Generated by Django 2.1.7 on 2019-03-30 22:12

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190330_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True),
        ),
    ]
