# Generated by Django 2.1.7 on 2019-04-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelquote',
            name='discounts',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
