# Generated by Django 2.1.7 on 2019-04-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_fuelquote_discounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelquote',
            name='discounts',
        ),
    ]
