# Generated by Django 2.1.7 on 2019-04-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_fuelquote_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelquote',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
