# Generated by Django 2.1.7 on 2019-04-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20190427_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelquote',
            name='delivery_date',
            field=models.DateField(),
        ),
    ]
