# Generated by Django 2.1.7 on 2019-04-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20190427_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelQuoteModifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_gallon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summer_modifier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_margin', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
