# Generated by Django 2.1.7 on 2019-04-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_fuelquotemodifiers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuelQuoteModifiers',
            new_name='FuelQuoteModifier',
        ),
    ]
