# Generated by Django 2.1.7 on 2019-04-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20190428_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelquote',
            name='price_per_gallon',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
