# Generated by Django 2.1.7 on 2019-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_fuelquote_price_per_gallon'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelquote',
            name='discounts',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
