# Generated by Django 2.1.7 on 2019-04-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_fuelquote_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelquote',
            name='delivery_street2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
