# Generated by Django 2.2 on 2019-04-28 20:28

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_fuelquote_delivery_street2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelquote',
            name='delivery_state',
            field=localflavor.us.models.USStateField(max_length=2, null=True),
        ),
    ]
