# Generated by Django 2.2 on 2019-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_auto_20190428_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelquote',
            name='delivery_street2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
